### ISSUE TITLE
Peer review 1 Locksmith 1DV450

### ISSUE THREAD

**Issue by vl222cu** [re222dv/Locksmith#1]
Hej Rasmus!

Då har jag gått igenom din applikation och kod och jag tycker absolut att du har gjort ett mycket bra jobb! Applikationens alla funktioner funkar utan problem och dina routes funkar fint, har inte lyckats hitta något säkerhetshål alls så du har skyddat din applikation väl :) Tyckte även att det var en smart lösning att använda samma formulär för både admin och users. 

Vad gäller koden så tycker jag att den är välkonstruerad och du har strukturerat upp den snyggt i de olika mapparna så att det är enkelt att navigera sig mellan alla sidor, speciellt i view-mappen då du hade en hel del olika vyer. 

För övrigt så gick installationen av applikationen bra enligt dina instruktioner ända fram till att jag startade servern, då ville inte din sida http://localhost:3000/locksmith visas alls. Fick istället lösa det genom att skriva rails server -b 0.0.0.0 och sedan gå in genom Preview-länken http://fierce-fireball-96-185708.euw1-2.nitrousbox.com/locksmith/signin. Då funkade det bra.

Jag har inte så mycket att säga gällande vad som behöver förbättras då jag tycker att din applikationen är väl genomförd :) 

Hälsningar Vivi

**Comment by Pajn** [comment]
Tack så mycket för genomgången. Inte testat Nitrous, det ska jag tänka på till nästa gång.
